---

commons:
  username: &username "dvinciguerra"

# general
title: The Vince blog
description: "vincebot chronicles"
keywords: "Daniel Vinciguerra, dvinciguerra, Vince, Software Engineer, Software Design, Tech Leader, Perl, Ruby"
author:
  name: "Daniel Vinciguerra"
  description: ""

domain: dvinciguerra.github.io
url: "https://vincebot.dev"
baseurl: ""

# social
github:
  username: *username

twitter:
  username: *username

# build
markdown: kramdown
permalink: /:title/

sass:
    style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  - Gemfile

# plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-spaceship

jekyll-spaceship:
  processors:
    - table-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  plantuml-processor:
    mode: default
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/

feed:
  tags: true
  posts_limit: 50
  path: /feed.atom
